/vis/open OGL
/vis/drawVolume
/vis/viewer/set/autoRefresh true 
/vis/scene/add/eventID                      
/vis/scene/add/trajectories smooth
#/vis/scene/add/hits
/vis/viewer/set/rotationStyle freeRotation 
#/vis/scene/endOfEventAction accumulate
/vis/scene/add/axes 0 0 0 30 mm            
#/vis/modeling/trajectories/create/drawByParticleID 
#/vis/modeling/trajectories/drawByCharge-0/set gamma green
#/vis/modeling/trajectories/drawByCharge-0/set e- red
#/vis/modeling/trajectories/drawByCharge-0/set p+ blue
#/vis/modeling/trajectories/drawByCharge-0/set neutron yellow
/vis/verbose 0 

